apps/croppedimages/urls.py
from django.urls import path

from . import views

app_name = 'croppedimages'

urlpatterns = [
    # Cropped image urls
    path('orig_image_upload/',
         views.OrigImageUploadView.as_view(),
         name="orig_image_upload_url"
         ),

    path('<int:pk>/crop_image/',
         views.OrigImageDetailView.as_view(),
         name="crop_orig_image_url"
         ),

    path('cropped_image_save/',
         views.CroppedImageSaveView.as_view(),
         name="crop_image_js_url"
         ),

    path('cropped_images_list/',
         views.CroppedImageListView.as_view(),
         name="cropped_images_list_url"
         ),

    path('<int:pk>/cropped_image/',
         views.CroppedImageDetailView.as_view(),
         name="cropped_image_detail_url"
         ),

    path('<int:pk>/delete_cropped_image/',
         views.CroppedImageDeleteView.as_view(),
         name="cropped_image_delete_url"
         ),

]

apps/dropzoneimages/urls.py
from django.urls import path
from . import views

app_name = 'dropzoneimages'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.DzImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.DzImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.DzImagesDeleteUrl.as_view(),
         name='dz_image_delete_url'),
]

apps/singleimages/urls.py
from django.urls import path

from . import views

app_name = 'singleimages'

urlpatterns = [
    # Single/orig image urls
    path('single_image_upload/',
         views.SingleImageUploadView.as_view(),
         name="single_image_upload_url"
         ),

    path('single_image_list/',
         views.SingleImageListView.as_view(),
         name="single_image_list_url"
         ),

    path('<int:pk>/single_image_Detail/',
         views.SingleImageDetailView.as_view(),
         name="single_image_detail_url"
         ),

    path('<int:pk>/delete_single_image/',
         views.SingleImageDeleteView.as_view(),
         name="single_image_delete_url"
         ),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    ########### User Account #############
    path('register/',
         views.register,
         name='register'
         ),

    path('profile/',
         views.profile,
         name='profile'
         ),

    path('registration_under_approval/',
         views.RegistrationUnderApproval.as_view(
             template_name='users/registration_under_approval.html'),
         name='registration_under_approval_url'
         ),

    path('',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'
         ),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'
         ),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
         ),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeTemplateView.as_view(), name="home_url"),
    path('', include('users.urls', namespace='users')),

    path('singleimages/', include("singleimages.urls", namespace="singleimages")),
    path('multipleimages/', include("multipleimages.urls", namespace="multipleimages")),
    path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('dropzoneimages/', include("dropzoneimages.urls", namespace="dropzoneimages")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/partials/_header.html
{% comment %} comment the whole header page if one or more apps are being deleted. {% endcomment %}

{% if not 'log' in request.path and not 'register' in request.path and not request.path == '/' %}
<div class="d-flex justify-content-lg-center my-3">
    <a href="{% url 'singleimages:single_image_upload_url' %}" class="btn btn-sm btn-info m-1" type="button">Single Image Upload</a>
    <a href="{% url 'multipleimages:multiple_images_upload_url' %}" class="btn btn-sm btn-primary m-1" type="button">Multiple Images Upload</a>
    <a href="{% url 'croppedimages:orig_image_upload_url' %}" class="btn btn-sm btn-secondary m-1" type="button">Cropped Image Upload</a>
    <a href="{% url 'dropzoneimages:imageset_create_url' %}" class="btn btn-sm btn-success m-1" type="button">Dropzone Image Upload</a>
</div>
<hr>
{% else %}
<div class="mt-5"></div>
{% endif %}

templates/partials/_leftbar.html
  <ul class="list-group mt-2">
    <li class="list-group-item active">
    Leftbar
    </li>
    {% if 'singleimages' in request.path %}
      <li class="list-group-item">
        <a href="{% url 'singleimages:single_image_list_url' %}"> Single Images List</a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'singleimages:single_image_upload_url' %}">Upload single image</a>
      </li>

    {% elif 'multipleimages' in request.path %}
      <li class="list-group-item">
        <a href="{% url 'multipleimages:multiple_image_list_url' %}"> Multiple Images List</a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'multipleimages:multiple_images_upload_url' %}">Upload Multiple images</a>
      </li>
    
    {% elif 'croppedimages' in request.path %}
        <li class="list-group-item">
        <a href="{% url 'croppedimages:cropped_images_list_url' %}"> Cropped Images List</a>
      </li>
      
    {% endif %}
    
  </ul>

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top fixed-top ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_url' %}">Django Image Upload</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="#">{{ request.user|capfirst }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:logout' %}">logout</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/partials/_paginator.html
    {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}

templates/partials/_scripts.html
{% load static %}
<script src="{% static 'js/vendor/jquerry.js' %}"></script>
<script src="{% static 'js/vendor/popper.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/lightbox_bs5.js' %}"></script>
<script src="{% static 'js/site_js.js' %}"></script>