apps/multipleimages/urls.py
from django.urls import path

from . import views

app_name = 'multipleimages'

urlpatterns = [
    path('multiple_images_upload/',
         views.MultipleImagesUploadView.as_view(),
         name="multiple_images_upload_url"
         ),

    path('multiple_image_list/',
         views.MultipleImageListView.as_view(),
         name="multiple_image_list_url"
         ),

    path('<int:pk>/delete_multi_image/',
         views.MultipleImageDeleteView.as_view(),
         name="multi_image_delete_url"
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeTemplateView.as_view(), name="home_url"),
    path('', include('users.urls', namespace='users')),

    path('singleimages/', include("singleimages.urls", namespace="singleimages")),
    path('multipleimages/', include("multipleimages.urls", namespace="multipleimages")),
    path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('dropzoneimages/', include("dropzoneimages.urls", namespace="dropzoneimages")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/multipleimages/models.py
import os

from django.db import models
from django.conf import settings
from django.core.validators import validate_image_file_extension
from django.utils.translation import gettext_lazy as _


User = settings.AUTH_USER_MODEL


class MultipleImageFile(models.Model):
    '''Upload Multiple images using django forms and models.'''

    user = models.ForeignKey(User,
                             related_name="multi_images",
                             on_delete=models.CASCADE
                             )

    image = models.ImageField(upload_to="images",
                              validators=[validate_image_file_extension])

    @property
    def get_imageurl(self):
        return self.image.url

    @property
    def get_imagepath(self):
        return self.image.path

    @property
    def get_filename(self):
        return os.path.split(self.image.path)[-1]

apps/multipleimages/forms.py
from django import forms
from django.core.validators import validate_image_file_extension
from .models import MultipleImageFile


class MultipleImagesUploadForm(forms.ModelForm):
    image = forms.FileField(
        validators=[validate_image_file_extension],
        widget=forms.ClearableFileInput()
    )

    class Meta:
        model = MultipleImageFile
        fields = ['image']


class CustomClearableFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

    def __init__(self, attrs=None):
        attrs = {'multiple': True} if attrs is None else {**attrs, 'multiple': True}
        super().__init__(attrs)

apps/multipleimages/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import MultipleImageFile
from .forms import MultipleImagesUploadForm


class MultipleImagesUploadView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = MultipleImagesUploadForm()
        context = {
            'form': form
        }
        return render(request, 'multipleimages/multipleimagefile_form.html', context)

    def post(self, *args, **kwargs):
        form = MultipleImagesUploadForm(
            self.request.POST, self.request.FILES)
        uploaded_images = self.request.FILES.getlist('image')
        if len(uploaded_images) > 1:
            multiple_files = True
            # Do something, if required, or simply delete this part.
        else:
            multiple_files = False
            # Do something else

        if form.is_valid:
            for index, file in enumerate(uploaded_images):
                self.request.FILES['image'] = file
                # or anything else you want to display/ or delete this part
                print(f"working on file {index + 1}:{file}")

                user = self.request.user
                img = MultipleImageFile(image=file, user=user)
                img.save()
        return HttpResponseRedirect(reverse_lazy("multipleimages:multiple_image_list_url"))


class MultipleImageListView(LoginRequiredMixin, ListView):
    model = MultipleImageFile
    context_object_name = 'multi_images'
    paginate_by = 50
    ordering = ['-id']

    def get_queryset(self):
        user = self.request.user
        qs = MultipleImageFile.objects.filter(user=user)
        return qs


class MultipleImageDeleteView(LoginRequiredMixin, DeleteView):
    model = MultipleImageFile
    context_object_name = "image"
    success_url = reverse_lazy("multipleimages:multiple_image_list_url")

apps/multipleimages/templates/multipleimages/multipleimagefile_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Confirm delete - Image
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-md-8 mt-2">
    <form action="" method="post">
    {% csrf_token %}
      <div class="alert alert-danger" role="alert">
      You are about to delete the Cropped Image {{ object.get_filename|capfirst }}.
      </div>
    <input type="submit" value="Confirm Delete" class="btn btn-outline-danger">
  </form>
</div>
{% endblock content %}

apps/multipleimages/templates/multipleimages/multipleimagefile_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-md-9">
        <legend class="border-bottom">Upload Multiple Images Using Django</legend>
        <form action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-sm btn-outline-info mt-2">Submit</button>
        </form>
    </div>
{% endblock content %}

apps/multipleimages/templates/multipleimages/multipleimagefile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Multiple images list
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-md-9 mt-2">
    <div class="row">
        {% for image in multi_images %}
        {% with image.get_imageurl as imgurl %}
        <div class="col-sm-3">
            <a href="{{ imgurl }}" data-toggle="lightbox" data-gallery="image-gallery">
                <img src="{{ imgurl }}" alt="" class="img-fluid mx-1 my-1" width="250px" height="250px" />
            </a>
            <a href="{% url 'multipleimages:multi_image_delete_url' image.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                <img src="{% static 'img/cross.png' %}" alt="" />
            </a>
        </div>
        {% endwith %}
        {%empty%}
        <div class="card">
            <div class="card-body">
                Nil image file uploaded yet!
            </div>
        </div>
        {% endfor %}
    </div>
    
</div>
{% endblock content %}