apps/dropzoneimages/urls.py
from django.urls import path
from . import views

app_name = 'dropzoneimages'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.DzImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.DzImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.DzImagesDeleteUrl.as_view(),
         name='dz_image_delete_url'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeTemplateView.as_view(), name="home_url"),
    path('', include('users.urls', namespace='users')),

    path('singleimages/', include("singleimages.urls", namespace="singleimages")),
    path('multipleimages/', include("multipleimages.urls", namespace="multipleimages")),
    path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('dropzoneimages/', include("dropzoneimages.urls", namespace="dropzoneimages")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/dropzoneimages/models.py
import os

from django.db import models
from django.conf import settings
from django.urls import reverse
from config.models import CreationModificationDateBase


class ImageSet(CreationModificationDateBase):
    name = models.CharField(
        max_length=100, help_text="eg. Delhi-trip, Tajmahal, flowers")
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='imagesets',
                             on_delete=models.CASCADE
                             )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dropzoneimages:imageset_detail_url", kwargs={"pk": self.pk})


class ImagesUpload(models.Model):
    image_set = models.ForeignKey('dropzoneimages.ImageSet',
                                  related_name="images",
                                  on_delete=models.CASCADE,
                                  help_text="Image Set of the uploading images"
                                  )
    image = models.ImageField(upload_to="dz_images")

    @property
    def get_imageurl(self):
        return self.image.url

    @property
    def get_imagepath(self):
        return self.image.path

    @property
    def get_filename(self):
        return os.path.split(self.image.path)[-1]

    def get_delete_url(self):
        return reverse("dropzoneimages:images_list_url", kwargs={"pk": self.image_set.id})

apps/dropzoneimages/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from django.views.generic import View
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import ImageSet, ImagesUpload


class ImageSetCreateView(LoginRequiredMixin, CreateView):
    model = ImageSet
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ImageSetListView(LoginRequiredMixin, ListView):
    model = ImageSet
    context_object_name = 'imageset_qs'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ImageSetDetailView(LoginRequiredMixin, DetailView):
    model = ImageSet
    context_object_name = 'imageset'


class DzImagesUploadView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        imageset_id = self.kwargs.get("pk")
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        context = {
            'imageset': imageset,
        }
        return render(request, 'dropzoneimages/imagesupload_form.html', context)

    def post(self, request, *args, **kwargs):
        imageset_id = self.kwargs.get("pk")
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        if self.request.method == 'POST':
            images = [self.request.FILES.get("file[%d]" % i)
                      for i in range(0, len(self.request.FILES))]
            for img in images:
                ImagesUpload.objects.create(image=img, image_set=imageset)

            message = f"Uploading images to the Imageset: {imageset}. \
                Automatic redirect to the images list after completion."

            redirect_to = reverse_lazy(
                "dropzoneimages:images_list_url", args=[imageset.id])
            return JsonResponse({"result": "result",
                                "message": message,
                                 "redirect_to": redirect_to,
                                 "files_length": len(images),
                                 },
                                status=200,
                                content_type="application/json"
                                )


class DzImagesListView(LoginRequiredMixin, ListView):
    model = ImagesUpload
    context_object_name = 'images'

    def get_queryset(self):
        imageset_id = self.kwargs.get('pk')
        return super().get_queryset().filter(image_set__id=imageset_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imageset_id = self.kwargs.get('pk')
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        context["imageset"] = imageset
        return context


class DzImagesDeleteUrl(LoginRequiredMixin, DeleteView):
    model = ImagesUpload

    def get_success_url(self):
        qs = self.get_object()
        return qs.get_delete_url()

apps/dropzoneimages/templates/dropzoneimages/imageset_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ imageset.name }} - ImageSet
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-md-8 mt-2">
    <div class="card">
    <div class="card-header">
        {{ imageset.name|capfirst }} - Image set
    </div>
    <div class="card-body">
        <h5 class="card-title">Description</h5>
        <p class="card-text">{{imageset.description}}</p>
        <a href="{% url 'dropzoneimages:upload_images_url' imageset.id %}" class="btn btn-primary">Upload images</a>
    </div>
    </div>    
</div>
{% endblock content %}

{% block shared_data %}
    {{ orig_image.id|json_script:"imageId" }}
{% endblock shared_data %}

apps/dropzoneimages/templates/dropzoneimages/imageset_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}
Create Dropzone Images set
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-md-6 offset-1">
        <h4 class="mb-4">Create Image Set for the uploading multiple images.</h4>
        <form action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form|crispy }}

            <button type="submit" class="btn btn-sm btn-outline-info mt-2">Submit</button>
        </form>
    </div>
{% endblock content %}

apps/dropzoneimages/templates/dropzoneimages/imagesupload_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Confirm delete - Image in {{ object.image_set.name }}
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-md-8 mt-2">
    <form action="" method="post">
    {% csrf_token %}
      <div class="alert alert-danger" role="alert">
      You are about to delete the Image {{ object.get_filename|capfirst }}.
      </div>
    <input type="submit" value="Confirm Delete" class="btn btn-outline-danger">
  </form>
</div>
{% endblock content %}

apps/dropzoneimages/templates/dropzoneimages/imagesupload_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block on_page_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/basic.css' %}" > 
  <link rel="stylesheet" type="text/css" href="{% static 'css/dropzone.css' %}" />
{% endblock on_page_css %}

{% block title %}
{{imageset.name|capfirst}} - Images upload
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-md-6 offset-1">
        <h4 class="mb-4">Upload images to {{ imageset.name|capfirst }} image set.</h4>
        <form action="{% url 'dropzoneimages:upload_images_url' imageset.id %}" method="post" enctype="multipart/form-data" class="dropzone dz" id="DzImageUpload" >
            {% csrf_token %}
            <div class="dz-default dz-message upload_client">
                Drag & Drop Image files here or <strong>click here</strong> to upload.
            </div>
        </form>
        <button id="imagesUploadBtn" type="submit" class="btn btn-sm btn-outline-info mt-2">Submit</button>
    </div>
{% endblock content %}

{% block on_page_js %}
<script src="{% static 'js/dropzone-min.js' %}"></script>

<script>
    {% include 'dropzoneimages/partials/_dzconfig.html' %}
</script>

{% endblock on_page_js %}

apps/dropzoneimages/templates/dropzoneimages/imagesupload_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Multiple images list
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-md-9 mt-2">
    <a type="button" class="btn btn-sm btn-outline-info mb-2" href="{% url 'dropzoneimages:upload_images_url' imageset.id %}">Upload More images</a>
    <div class="row">
        {% for image in images %}
        {% with image.get_imageurl as imgurl %}
        <div class="col-sm-3">
            <a href="{{ imgurl }}" data-toggle="lightbox" data-gallery="image-gallery">
                <img src="{{ imgurl }}" alt="" class="img-fluid mx-1 my-1" width="250px" height="250px" />
            </a>
            <a href="{% url 'dropzoneimages:dz_image_delete_url' image.image_set.id image.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                <img src="{% static 'img/cross.png' %}" alt="" />
            </a>
        </div>
        {% endwith %}
        {% endfor %}
    </div>
    
</div>
{% endblock content %}